# Copyright 2025 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  oci_annotations.yaml
#   timestamp: 2026-07-28T13:45:46+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel

from transpiler_mate import TranspilerBaseModel


class OciAnnotations(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    org_opencontainers_image_title: Annotated[
        str | None, Field(alias="org.opencontainers.image.title")
    ] = None
    org_opencontainers_image_description: Annotated[
        str | None, Field(alias="org.opencontainers.image.description")
    ] = None
    org_opencontainers_image_version: Annotated[
        str | None, Field(alias="org.opencontainers.image.version")
    ] = None
    org_opencontainers_image_source: Annotated[
        str | None, Field(alias="org.opencontainers.image.source")
    ] = None
    org_opencontainers_image_revision: Annotated[
        str | None, Field(alias="org.opencontainers.image.revision")
    ] = None
    org_opencontainers_image_licenses: Annotated[
        str | None, Field(alias="org.opencontainers.image.licenses")
    ] = None
    org_cwl_entrypoint: Annotated[str | None, Field(alias="org.cwl.entrypoint")] = None
    org_cwl_spec: Annotated[str | None, Field(alias="org.cwl.spec")] = None
    org_cwl_type: Annotated[str | None, Field(alias="org.cwl.type")] = None


class Model(RootModel[OciAnnotations]):
    root: OciAnnotations
