# Copyright 2025 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  software_application.yaml
#   timestamp: 2026-07-28T13:45:21+00:00

from __future__ import annotations

from datetime import date
from typing import Annotated, Literal

from pydantic import (
    AliasChoices,
    AnyUrl,
    AwareDatetime,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)

from transpiler_mate import TranspilerBaseModel


class Organization(TranspilerBaseModel):
    """
    An organization such as a school, NGO, corporation, club, etc.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[
        Literal["https://schema.org/Organization"], Field(alias="@type")
    ] = "https://schema.org/Organization"
    name: str = Field(
        ...,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    """
    The name of the item.
    """
    email: EmailStr | list[EmailStr] | None = Field(
        default=None,
        validation_alias=AliasChoices("email", "https://schema.org/email"),
        serialization_alias="https://schema.org/email",
    )
    """
    Email address.
    """
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )
    """
    The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.

    """


class Person(TranspilerBaseModel):
    """
    A person (alive, dead, undead, or fictional).
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[
        Literal["https://schema.org/Person"], Field(alias="@type")
    ] = "https://schema.org/Person"
    given_name: Annotated[str, Field(alias="givenName")]
    """
    Given name. In the U.S., the first name of a Person.
    """
    family_name: Annotated[str, Field(alias="familyName")]
    """
    Family name. In the U.S., the last name of a Person.
    """
    email: EmailStr | list[EmailStr] = Field(
        ...,
        validation_alias=AliasChoices("email", "https://schema.org/email"),
        serialization_alias="https://schema.org/email",
    )
    """
    Email address.
    """
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )
    """
    The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.

    """
    affiliation: Organization | list[Organization] = Field(
        ...,
        validation_alias=AliasChoices("affiliation", "https://schema.org/affiliation"),
        serialization_alias="https://schema.org/affiliation",
    )
    """
    An organization that this person is affiliated with. For example, a school/university, a club, or a team.
    """


class Role(TranspilerBaseModel):
    """
    Represents additional information about a relationship or property.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[Literal["https://schema.org/Role"], Field(alias="@type")] = (
        "https://schema.org/Role"
    )
    role_name: Annotated[str, Field(alias="roleName")]
    """
    A role played, performed or filled by a person or organization.
    """
    start_date: Annotated[date | None, Field(alias="startDate")] = None
    """
    The start date and time of the item
    """
    end_date: Annotated[date | None, Field(alias="endDate")] = None
    """
    The end date and time of the item
    """
    additional_type: Annotated[AnyUrl | None, Field(alias="additionalType")] = None
    """
    An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax.
    """


class AuthorRole(Role):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    author: Person = Field(
        ...,
        validation_alias=AliasChoices("author", "https://schema.org/author"),
        serialization_alias="https://schema.org/author",
    )


class ContributorRole(Role):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    contributor: Person = Field(
        ...,
        validation_alias=AliasChoices("contributor", "https://schema.org/contributor"),
        serialization_alias="https://schema.org/contributor",
    )


class DefinedTerm(TranspilerBaseModel):
    """
    A word, name, acronym, phrase, etc. with a formal definition. Often used in the context of category or subject classification, glossaries or dictionaries, product or creative work types, etc. Use the name property for the term being defined, use termCode if the term has an alpha-numeric code allocated, use description to provide the definition of the term.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[
        Literal["https://schema.org/DefinedTerm"], Field(alias="@type")
    ] = "https://schema.org/DefinedTerm"
    name: str | None = Field(
        default=None,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    """
    The name of the item.
    """
    description: str | None = Field(
        default=None,
        validation_alias=AliasChoices("description", "https://schema.org/description"),
        serialization_alias="https://schema.org/description",
    )
    """
    A description of the item.
    """
    term_code: Annotated[str | None, Field(alias="termCode")] = None
    """
    A code that identifies this [[DefinedTerm]] within a [[DefinedTermSet]].
    """
    in_defined_term_set: Annotated[AnyUrl | None, Field(alias="inDefinedTermSet")] = (
        None
    )
    """
    A [[DefinedTermSet]] that contains this term.
    """


class CreativeWork(TranspilerBaseModel):
    """
    The most generic kind of creative work, including books, movies, photographs, software programs, etc.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[
        Literal["https://schema.org/CreativeWork"], Field(alias="@type")
    ] = "https://schema.org/CreativeWork"
    name: str | None = Field(
        default=None,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    """
    The name of the item.
    """
    url: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices("url", "https://schema.org/url"),
        serialization_alias="https://schema.org/url",
    )
    """
    URL of the item.
    """
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )
    """
    The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.

    """


class ImageObject(TranspilerBaseModel):
    """
    An image file.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[
        Literal["https://schema.org/ImageObject"], Field(alias="@type")
    ] = "https://schema.org/ImageObject"
    content_url: Annotated[AnyUrl | None, Field(alias="contentUrl")] = None
    """
    Actual bytes of the media object, for example the image file or video file.
    """
    caption: str | None = Field(
        default=None,
        validation_alias=AliasChoices("caption", "https://schema.org/caption"),
        serialization_alias="https://schema.org/caption",
    )
    """
    The caption for this object.
    """
    encoding_format: Annotated[str | None, Field(alias="encodingFormat")] = None
    """
    Media type typically expressed using a MIME format (see [IANA site](http://www.iana.org/assignments/media-types/media-types.xhtml) and [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)), e.g. application/zip for a SoftwareApplication binary, audio/mpeg for .mp3 etc.

    """
    width: int | None = Field(
        default=None,
        validation_alias=AliasChoices("width", "https://schema.org/width"),
        serialization_alias="https://schema.org/width",
    )
    """
    The width of the item.
    """
    height: int | None = Field(
        default=None,
        validation_alias=AliasChoices("height", "https://schema.org/height"),
        serialization_alias="https://schema.org/height",
    )
    """
    The width of the item.
    """


class SoftwareApplication(TranspilerBaseModel):
    """
    A software application.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[
        Literal["https://schema.org/SoftwareApplication"], Field(alias="@type")
    ] = "https://schema.org/SoftwareApplication"
    name: str = Field(
        ...,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    """
    The name of the item.
    """
    description: str = Field(
        ...,
        validation_alias=AliasChoices("description", "https://schema.org/description"),
        serialization_alias="https://schema.org/description",
    )
    """
    A description of the item.
    """
    date_created: Annotated[date | AwareDatetime, Field(alias="dateCreated")]
    """
    The date on which the CreativeWork was created or the item was added to a DataFeed.
    """
    license: CreativeWork | AnyUrl | list[CreativeWork | AnyUrl] = Field(
        ...,
        validation_alias=AliasChoices("license", "https://schema.org/license"),
        serialization_alias="https://schema.org/license",
    )
    """
    A license document that applies to this content, typically indicated by URL.
    """
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )
    """
    The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.

    """
    same_as: Annotated[AnyUrl | list[AnyUrl] | None, Field(alias="sameAs")] = None
    """
    URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
    """
    keywords: str | AnyUrl | DefinedTerm | list[str | AnyUrl | DefinedTerm] | None = (
        Field(
            default=None,
            validation_alias=AliasChoices("keywords", "https://schema.org/keywords"),
            serialization_alias="https://schema.org/keywords",
        )
    )
    """
    Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.
    """
    operating_system: Annotated[
        str | list[str] | None, Field(alias="operatingSystem")
    ] = None
    """
    Operating systems supported (Windows 7, OS X 10.6, Android 1.6).
    """
    software_requirements: Annotated[
        str | AnyUrl | list[str | AnyUrl] | None, Field(alias="softwareRequirements")
    ] = None
    """
    Component dependency requirements for application. This includes runtime environments and shared libraries that are not included in the application distribution package, but required to run the application (examples: DirectX, Java or .NET runtime).
    """
    software_version: Annotated[str, Field(alias="softwareVersion")]
    """
    Version of the software instance.
    """
    software_help: Annotated[
        CreativeWork | list[CreativeWork], Field(alias="softwareHelp")
    ]
    """
    Software application help.
    """
    publisher: Organization = Field(
        ...,
        validation_alias=AliasChoices("publisher", "https://schema.org/publisher"),
        serialization_alias="https://schema.org/publisher",
    )
    """
    The publisher of the article in question.
    """
    author: AuthorRole | Person | list[AuthorRole | Person] = Field(
        ...,
        validation_alias=AliasChoices("author", "https://schema.org/author"),
        serialization_alias="https://schema.org/author",
    )
    """
    The author of this content or rating. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably.
    """
    contributor: ContributorRole | Person | list[ContributorRole | Person] | None = (
        Field(
            default=None,
            validation_alias=AliasChoices(
                "contributor", "https://schema.org/contributor"
            ),
            serialization_alias="https://schema.org/contributor",
        )
    )
    """
    A secondary contributor to the CreativeWork or Event.
    """
    thumbnail: ImageObject | None = Field(
        default=None,
        validation_alias=AliasChoices("thumbnail", "https://schema.org/thumbnail"),
        serialization_alias="https://schema.org/thumbnail",
    )
    """
    Thumbnail image for an image or video.
    """


class SoftwareSourceCode(TranspilerBaseModel):
    """
    Computer programming source code.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: Annotated[
        Literal["https://schema.org/SoftwareSourceCode"], Field(alias="@type")
    ] = "https://schema.org/SoftwareSourceCode"
    code_repository: AnyUrl = Field(
        ...,
        validation_alias=AliasChoices(
            "codeRepository", "https://schema.org/codeRepository"
        ),
        serialization_alias="https://schema.org/codeRepository",
    )
    """
    Link to the repository where the un-compiled, human readable code and related code is located (SVN, GitHub, CodePlex).
    """
    target_product: SoftwareApplication = Field(
        ...,
        validation_alias=AliasChoices(
            "targetProduct", "https://schema.org/targetProduct"
        ),
        serialization_alias="https://schema.org/targetProduct",
    )
    """
    Target Operating System / Product to which the code applies. If applies to several versions, just the product name can be used.
    """
    continuous_integration: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "continuousIntegration", "https://schema.org/continuousIntegration"
        ),
        serialization_alias="https://schema.org/continuousIntegration",
    )
    issue_tracker: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "issueTracker", "https://schema.org/issueTracker"
        ),
        serialization_alias="https://schema.org/issueTracker",
    )
    related_link: AnyUrl | list[AnyUrl] | None = Field(
        default=None,
        validation_alias=AliasChoices("relatedLink", "https://schema.org/relatedLink"),
        serialization_alias="https://schema.org/relatedLink",
    )


class Model(RootModel[SoftwareApplication]):
    root: SoftwareApplication
