# Copyright 2025-2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  software_application.yaml
#   timestamp: 2026-03-05T14:51:11+00:00

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import AliasChoices, AnyUrl, EmailStr, Field, RootModel

from transpiler_mate import TranspilerBaseModel


class Organization(TranspilerBaseModel):
    """
    An organization such as a school, NGO, corporation, club, etc.
    """

    field_type: Literal["https://schema.org/Organization"] = Field(
        "https://schema.org/Organization", alias="@type"
    )
    name: str = Field(
        ...,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    email: EmailStr | list[EmailStr] | None = Field(
        default=None,
        validation_alias=AliasChoices("email", "https://schema.org/email"),
        serialization_alias="https://schema.org/email",
    )
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )


class Person(TranspilerBaseModel):
    """
    A person (alive, dead, undead, or fictional).
    """

    field_type: Literal["https://schema.org/Person"] = Field(
        "https://schema.org/Person", alias="@type"
    )
    given_name: str = Field(
        ...,
        validation_alias=AliasChoices("givenName", "https://schema.org/givenName"),
        serialization_alias="https://schema.org/givenName",
    )
    family_name: str = Field(
        ...,
        validation_alias=AliasChoices("familyName", "https://schema.org/familyName"),
        serialization_alias="https://schema.org/familyName",
    )
    email: EmailStr | list[EmailStr] = Field(
        ...,
        validation_alias=AliasChoices("email", "https://schema.org/email"),
        serialization_alias="https://schema.org/email",
    )
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )
    affiliation: Organization | list[Organization] = Field(
        ...,
        validation_alias=AliasChoices("affiliation", "https://schema.org/affiliation"),
        serialization_alias="https://schema.org/affiliation",
    )


class Role(TranspilerBaseModel):
    """
    Represents additional information about a relationship or property.
    """

    field_type: Literal["https://schema.org/Role"] = Field(
        "https://schema.org/Role", alias="@type"
    )
    role_name: str = Field(
        ...,
        validation_alias=AliasChoices("roleName", "https://schema.org/roleName"),
        serialization_alias="https://schema.org/roleName",
    )
    start_date: date | None = Field(
        default=None,
        validation_alias=AliasChoices("startDate", "https://schema.org/startDate"),
        serialization_alias="https://schema.org/startDate",
    )
    end_date: date | None = Field(
        default=None,
        validation_alias=AliasChoices("endDate", "https://schema.org/endDate"),
        serialization_alias="https://schema.org/endDate",
    )
    additional_type: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "additionalType", "https://schema.org/additionalType"
        ),
        serialization_alias="https://schema.org/additionalType",
    )


class AuthorRole(Role):
    author: Person = Field(
        ...,
        validation_alias=AliasChoices("author", "https://schema.org/author"),
        serialization_alias="https://schema.org/author",
    )


class ContributorRole(Role):
    contributor: Person = Field(
        ...,
        validation_alias=AliasChoices("contributor", "https://schema.org/contributor"),
        serialization_alias="https://schema.org/contributor",
    )


class DefinedTerm(TranspilerBaseModel):
    """
    A word, name, acronym, phrase, etc. with a formal definition. Often used in the context of category or subject classification, glossaries or dictionaries, product or creative work types, etc. Use the name property for the term being defined, use termCode if the term has an alpha-numeric code allocated, use description to provide the definition of the term.
    """

    field_type: Literal["https://schema.org/DefinedTerm"] = Field(
        "https://schema.org/DefinedTerm", alias="@type"
    )
    name: str | None = Field(
        default=None,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    description: str | None = Field(
        default=None,
        validation_alias=AliasChoices("description", "https://schema.org/description"),
        serialization_alias="https://schema.org/description",
    )
    term_code: str | None = Field(
        default=None,
        validation_alias=AliasChoices("termCode", "https://schema.org/termCode"),
        serialization_alias="https://schema.org/termCode",
    )
    in_defined_term_set: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "inDefinedTermSet", "https://schema.org/inDefinedTermSet"
        ),
        serialization_alias="https://schema.org/inDefinedTermSet",
    )


class CreativeWork(TranspilerBaseModel):
    """
    The most generic kind of creative work, including books, movies, photographs, software programs, etc.
    """

    field_type: Literal["https://schema.org/CreativeWork"] = Field(
        "https://schema.org/CreativeWork", alias="@type"
    )
    name: str | None = Field(
        default=None,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    url: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices("url", "https://schema.org/url"),
        serialization_alias="https://schema.org/url",
    )
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )


class ImageObject(TranspilerBaseModel):
    """
    An image file.
    """

    field_type: Literal["https://schema.org/ImageObject"] = Field(
        "https://schema.org/ImageObject", alias="@type"
    )
    content_url: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices("contentUrl", "https://schema.org/contentUrl"),
        serialization_alias="https://schema.org/contentUrl",
    )
    caption: str | None = Field(
        default=None,
        validation_alias=AliasChoices("caption", "https://schema.org/caption"),
        serialization_alias="https://schema.org/caption",
    )
    encoding_format: str | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "encodingFormat", "https://schema.org/encodingFormat"
        ),
        serialization_alias="https://schema.org/encodingFormat",
    )
    width: int | None = Field(
        default=None,
        validation_alias=AliasChoices("width", "https://schema.org/width"),
        serialization_alias="https://schema.org/width",
    )
    height: int | None = Field(
        default=None,
        validation_alias=AliasChoices("height", "https://schema.org/height"),
        serialization_alias="https://schema.org/height",
    )


class SoftwareApplication(TranspilerBaseModel):
    """
    A software application.
    """

    field_type: Literal["https://schema.org/SoftwareApplication"] = Field(
        "https://schema.org/SoftwareApplication", alias="@type"
    )
    name: str = Field(
        ...,
        validation_alias=AliasChoices("name", "https://schema.org/name"),
        serialization_alias="https://schema.org/name",
    )
    description: str = Field(
        ...,
        validation_alias=AliasChoices("description", "https://schema.org/description"),
        serialization_alias="https://schema.org/description",
    )
    date_created: date | datetime = Field(
        ...,
        validation_alias=AliasChoices("dateCreated", "https://schema.org/dateCreated"),
        serialization_alias="https://schema.org/dateCreated",
    )
    license: CreativeWork | AnyUrl | list[CreativeWork | AnyUrl] = Field(
        ...,
        validation_alias=AliasChoices("license", "https://schema.org/license"),
        serialization_alias="https://schema.org/license",
    )
    identifier: AnyUrl | str | None = Field(
        default=None,
        validation_alias=AliasChoices("identifier", "https://schema.org/identifier"),
        serialization_alias="https://schema.org/identifier",
    )
    same_as: AnyUrl | list[AnyUrl] | None = Field(
        default=None,
        validation_alias=AliasChoices("sameAs", "https://schema.org/sameAs"),
        serialization_alias="https://schema.org/sameAs",
    )
    keywords: str | AnyUrl | DefinedTerm | list[str | AnyUrl | DefinedTerm] | None = (
        Field(
            default=None,
            validation_alias=AliasChoices("keywords", "https://schema.org/keywords"),
            serialization_alias="https://schema.org/keywords",
        )
    )
    operating_system: str | list[str] | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "operatingSystem", "https://schema.org/operatingSystem"
        ),
        serialization_alias="https://schema.org/operatingSystem",
    )
    software_requirements: str | AnyUrl | list[str | AnyUrl] | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "softwareRequirements", "https://schema.org/softwareRequirements"
        ),
        serialization_alias="https://schema.org/softwareRequirements",
    )
    software_version: str = Field(
        ...,
        validation_alias=AliasChoices(
            "softwareVersion", "https://schema.org/softwareVersion"
        ),
        serialization_alias="https://schema.org/softwareVersion",
    )
    software_help: CreativeWork | list[CreativeWork] = Field(
        ...,
        validation_alias=AliasChoices(
            "softwareHelp", "https://schema.org/softwareHelp"
        ),
        serialization_alias="https://schema.org/softwareHelp",
    )
    publisher: Organization = Field(
        ...,
        validation_alias=AliasChoices("publisher", "https://schema.org/publisher"),
        serialization_alias="https://schema.org/publisher",
    )
    author: AuthorRole | Person | list[AuthorRole | Person] = Field(
        ...,
        validation_alias=AliasChoices("author", "https://schema.org/author"),
        serialization_alias="https://schema.org/author",
    )
    contributor: ContributorRole | Person | list[ContributorRole | Person] | None = (
        Field(
            default=None,
            validation_alias=AliasChoices(
                "contributor", "https://schema.org/contributor"
            ),
            serialization_alias="https://schema.org/contributor",
        )
    )
    thumbnail: ImageObject | None = Field(
        default=None,
        validation_alias=AliasChoices("thumbnail", "https://schema.org/thumbnail"),
        serialization_alias="https://schema.org/thumbnail",
    )


class SoftwareSourceCode(TranspilerBaseModel):
    """
    Computer programming source code.
    """

    field_type: Literal["https://schema.org/SoftwareSourceCode"] = Field(
        "https://schema.org/SoftwareSourceCode", alias="@type"
    )
    code_repository: AnyUrl = Field(
        ...,
        validation_alias=AliasChoices(
            "codeRepository", "https://schema.org/codeRepository"
        ),
        serialization_alias="https://schema.org/codeRepository",
    )
    target_product: SoftwareApplication = Field(
        ...,
        validation_alias=AliasChoices(
            "targetProduct", "https://schema.org/targetProduct"
        ),
        serialization_alias="https://schema.org/targetProduct",
    )
    continuous_integration: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "continuousIntegration", "https://schema.org/continuousIntegration"
        ),
        serialization_alias="https://schema.org/continuousIntegration",
    )
    issue_tracker: AnyUrl | None = Field(
        default=None,
        validation_alias=AliasChoices(
            "issueTracker", "https://schema.org/issueTracker"
        ),
        serialization_alias="https://schema.org/issueTracker",
    )
    related_link: AnyUrl | list[AnyUrl] | None = Field(
        default=None,
        validation_alias=AliasChoices("relatedLink", "https://schema.org/relatedLink"),
        serialization_alias="https://schema.org/relatedLink",
    )


class Model(RootModel[SoftwareApplication]):
    root: SoftwareApplication
