# Copyright 2025 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  ogcapi_records.yaml
#   timestamp: 2026-07-28T13:45:34+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import (
    AnyUrl,
    AwareDatetime,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)

from transpiler_mate import TranspilerBaseModel


class Concept(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str
    """
    An identifier for the concept.
    """
    title: str | None = None
    """
    A human readable title for the concept.
    """
    description: str | None = None
    """
    A human readable description for the concept.
    """
    url: AnyUrl | None = None
    """
    A URI providing further description of the concept.
    """


class Theme(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    concepts: Annotated[list[Concept], Field(min_length=1)]
    """
    One or more entity/concept identifiers from this knowledge system. it is recommended that a resolvable URI be used for each entity/concept identifier.
    """
    scheme: str
    """
    An identifier for the knowledge organization system used to classify the resource.  It is recommended that the identifier be a resolvable URI.  The list of schemes used in a searchable catalog can be determined by inspecting the server's OpenAPI document or, if the server implements CQL2, by exposing a queryable (e.g. named `scheme`) and enumerating the list of schemes in the queryable's schema definition.
    """


class Dir(Enum):
    """
    The direction for text in this language. The default, `ltr` (left-to-right), represents the most common situation. However, care should be taken to set the value of `dir` appropriately if the language direction is not `ltr`. Other values supported are `rtl` (right-to-left), `ttb` (top-to-bottom), and `btt` (bottom-to-top).
    """

    LTR = "ltr"
    RTL = "rtl"
    TTB = "ttb"
    BTT = "btt"


class Language(TranspilerBaseModel):
    """
    The language used for textual values in this record.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    code: str
    """
    The language tag as per RFC-5646.
    """
    name: Annotated[str | None, Field(min_length=1)] = None
    """
    The untranslated name of the language.
    """
    alternate: str | None = None
    """
    The name of the language in another well-understood language, usually English.
    """
    dir: Dir | None = Dir.LTR
    """
    The direction for text in this language. The default, `ltr` (left-to-right), represents the most common situation. However, care should be taken to set the value of `dir` appropriately if the language direction is not `ltr`. Other values supported are `rtl` (right-to-left), `ttb` (top-to-bottom), and `btt` (bottom-to-top).
    """


class Format1(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: str
    media_type: Annotated[str | None, Field(alias="mediaType")] = None


class Format2(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: str | None = None
    media_type: Annotated[str, Field(alias="mediaType")]


class Roles(RootModel[list[str]]):
    """
    The list of duties, job functions or permissions assigned by the system and associated with the context of this member.
    """

    root: Annotated[list[str], Field(min_length=1)]
    """
    The list of duties, job functions or permissions assigned by the system and associated with the context of this member.
    """


class LinkBase(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    rel: str | None = None
    """
    The type or semantics of the relation.
    """
    type: str | None = None
    """
    A hint indicating what the media type of the result of dereferencing the link should be.
    """
    hreflang: str | None = None
    """
    A hint indicating what the language of the result of dereferencing the link should be.
    """
    title: str | None = None
    """
    Used to label the destination of a link such that it can be used as a human-readable identifier.
    """
    length: int | None = None
    created: AwareDatetime | None = None
    """
    Date of creation of the resource pointed to by the link.
    """
    updated: AwareDatetime | None = None
    """
    Most recent date on which the resource pointed to by the link was changed.
    """


class Link(LinkBase):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    href: str


class LinkTemplate(LinkBase):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    uri_template: Annotated[str, Field(alias="uriTemplate")]
    """
    Supplies a resolvable URI to a remote resource (or resource fragment).
    """
    var_base: Annotated[AnyUrl | None, Field(alias="varBase")] = None
    """
    The base URI to which the variable name can be appended to retrieve the definition of the variable as a JSON Schema fragment.
    """
    variables: dict[str, Any] | None = None
    """
    This object contains one key per substitution variable in the templated URL.  Each key defines the schema of one substitution variable using a JSON Schema fragment and can thus include things like the data type of the variable, enumerations, minimum values, maximum values, etc.
    """


class Rel(str, Enum):
    ICON = "icon"


class Logo(Link):
    """
    Graphic identifying a contact. The link relation should be `icon` and the media type should be an image media type.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    rel: Rel
    type: str
    """
    A hint indicating what the media type of the result of dereferencing the link should be.
    """


class Phone(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    value: Annotated[str, Field(pattern="^\\+[1-9]{1}[0-9]{3,14}$")]
    """
    The value is the phone number itself.
    """
    roles: Annotated[list[str] | None, Field(min_length=1)] = None
    """
    The list of duties, job functions or permissions assigned by the system and associated with the context of this member.
    """


class Email(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    value: EmailStr
    """
    The value is the email number itself.
    """
    roles: Annotated[list[str] | None, Field(min_length=1)] = None
    """
    The list of duties, job functions or permissions assigned by the system and associated with the context of this member.
    """


class Address(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    delivery_point: Annotated[list[str] | None, Field(alias="deliveryPoint")] = None
    """
    Address lines for the location.
    """
    city: str | None = None
    """
    City for the location.
    """
    administrative_area: Annotated[str | None, Field(alias="administrativeArea")] = None
    """
    State or province of the location.
    """
    postal_code: Annotated[str | None, Field(alias="postalCode")] = None
    """
    ZIP or other postal code.
    """
    country: str | None = None
    """
    Country of the physical address.  ISO 3166-1 is recommended.
    """
    roles: Annotated[list[str] | None, Field(min_length=1)] = None
    """
    The list of duties, job functions or permissions assigned by the system and associated with the context of this member.
    """


class Contact1(TranspilerBaseModel):
    """
    Identification of, and means of communication with, person responsible
    for the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    identifier: str | None = None
    """
    A value uniquely identifying a contact.
    """
    name: str
    """
    The name of the responsible person.
    """
    position: str | None = None
    """
    The name of the role or position of the responsible person taken from the organization's formal organizational hierarchy or chart.
    """
    organization: str | None = None
    """
    Organization/affiliation of the contact.
    """
    logo: Logo | None = None
    """
    Graphic identifying a contact. The link relation should be `icon` and the media type should be an image media type.
    """
    phones: list[Phone] | None = None
    """
    Telephone numbers at which contact can be made.  The type of
    phone number is indicated using the roles property.
    """
    emails: list[Email] | None = None
    """
    Email addresses at which contact can be made.  The type of
    email address is indicated using the roles property.
    """
    addresses: list[Address] | None = None
    """
    Physical location at which contact can be made.  The type of
    address is indicated using the roles property.
    """
    links: list[Link] | None = None
    """
    On-line information about the contact.
    """
    hours_of_service: Annotated[str | None, Field(alias="hoursOfService")] = None
    """
    Time period when the contact can be contacted.
    """
    contact_instructions: Annotated[str | None, Field(alias="contactInstructions")] = (
        None
    )
    """
    Supplemental instructions on how or when to contact the
    responsible party. The roles property is used to associate
    a set of named duties, job functions and/or permissions
    associated with this contact. (e.g. developer,
    administrator, etc.).
    """
    roles: Annotated[list[str] | None, Field(min_length=1)] = None
    """
    The list of duties, job functions or permissions assigned by the system and associated with the context of this member.
    """


class Logo1(Logo):
    """
    Graphic identifying a contact. The link relation should be `icon` and the media type should be an image media type.
    """


class Contact2(TranspilerBaseModel):
    """
    Identification of, and means of communication with, person responsible
    for the resource.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    identifier: str | None = None
    """
    A value uniquely identifying a contact.
    """
    name: str | None = None
    """
    The name of the responsible person.
    """
    position: str | None = None
    """
    The name of the role or position of the responsible person taken from the organization's formal organizational hierarchy or chart.
    """
    organization: str
    """
    Organization/affiliation of the contact.
    """
    logo: Logo1 | None = None
    """
    Graphic identifying a contact. The link relation should be `icon` and the media type should be an image media type.
    """
    phones: list[Phone] | None = None
    """
    Telephone numbers at which contact can be made.  The type of
    phone number is indicated using the roles property.
    """
    emails: list[Email] | None = None
    """
    Email addresses at which contact can be made.  The type of
    email address is indicated using the roles property.
    """
    addresses: list[Address] | None = None
    """
    Physical location at which contact can be made.  The type of
    address is indicated using the roles property.
    """
    links: list[Link] | None = None
    """
    On-line information about the contact.
    """
    hours_of_service: Annotated[str | None, Field(alias="hoursOfService")] = None
    """
    Time period when the contact can be contacted.
    """
    contact_instructions: Annotated[str | None, Field(alias="contactInstructions")] = (
        None
    )
    """
    Supplemental instructions on how or when to contact the
    responsible party. The roles property is used to associate
    a set of named duties, job functions and/or permissions
    associated with this contact. (e.g. developer,
    administrator, etc.).
    """
    roles: Annotated[list[str] | None, Field(min_length=1)] = None
    """
    The list of duties, job functions or permissions assigned by the system and associated with the context of this member.
    """


class ExternalId(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    scheme: str | None = None
    """
    A reference to an authority or identifier for a knowledge organization system from which the external identifier was obtained. It is recommended that the identifier be a resolvable URI.
    """
    value: str
    """
    The value of the identifier.
    """


class RecordCommonProperties(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    version: str | None = "1"
    created: AwareDatetime | None = None
    """
    The date this record was created in the server.
    """
    updated: AwareDatetime | None = None
    """
    The most recent date on which the record was changed.
    """
    type: str | None = None
    """
    The nature or genre of the resource. The value should be a code, convenient for filtering records. Where available, a link to the canonical URI of the record type resource will be added to the 'links' property.
    """
    title: str | None = None
    """
    A human-readable name given to the resource.
    """
    description: str | None = None
    """
    A free-text account of the resource.
    """
    keywords: list[str] | None = None
    """
    The topic or topics of the resource. Typically represented using free-form keywords, tags, key phrases, or classification codes.
    """
    themes: Annotated[list[Theme] | None, Field(min_length=1)] = None
    """
    A knowledge organization system used to classify the resource.
    """
    language: Language | None = None
    """
    The language used for textual values in this record representation.
    """
    languages: list[Language] | None = None
    """
    This list of languages in which this record is available.
    """
    resource_languages: Annotated[
        list[Language] | None, Field(alias="resourceLanguages")
    ] = None
    """
    The list of languages in which the resource described by this record is available.
    """
    external_ids: Annotated[list[ExternalId] | None, Field(alias="externalIds")] = None
    """
    An identifier for the resource assigned by an external (to the catalog) entity.
    """
    formats: list[Format1 | Format2] | None = None
    """
    A list of available distributions of the resource.
    """
    contacts: list[Contact1 | Contact2] | None = None
    """
    A list of contacts qualified by their role(s) in association to the record or the resource described by the record.
    """
    license: str | None = None
    """
    A legal document under which the resource is made available. If the resource is being made available under a common license then use an SPDX license id (https://spdx.org/licenses/). If the resource is being made available under multiple common licenses then use an SPDX license expression v2.3 string (https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/) If the resource is being made available under one or more licenses that haven't been assigned an SPDX identifier or one or more custom licenses then use a string value of 'other' and include one or more links (rel="license") in the `link` section of the record to the file(s) that contains the text of the license(s). There is also the case of a resource that is private or unpublished and is thus unlicensed; in this case do not register such a resource in the catalog in the first place since there is no point in making such a resource discoverable.
    """
    rights: str | None = None
    """
    A statement that concerns all rights not addressed by the license such as a copyright statement.
    """


class Interval(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}$")]


class Interval1(RootModel[str]):
    root: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$")
    ]


class Interval2(Enum):
    FIELD__ = ".."


class Time(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    date: Annotated[str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}$")] = None
    timestamp: Annotated[
        str | None,
        Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"),
    ] = None
    interval: Annotated[
        list[Interval | Interval1 | Interval2] | None, Field(max_length=2, min_length=2)
    ] = None
    resolution: str | None = None
    """
    Minimum time period resolvable in the dataset, as an ISO 8601 duration.
    """


class PointGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: str = "Point"
    coordinates: Annotated[list[float], Field(min_length=2)]


class Coordinate(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class MultipointGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: str = "MultiPoint"
    coordinates: list[Coordinate]


class LinestringGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: str = "LineString"
    coordinates: Annotated[list[Coordinate], Field(min_length=2)]


class Coordinate2Item(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Coordinate2(RootModel[list[Coordinate2Item]]):
    root: Annotated[list[Coordinate2Item], Field(min_length=2)]


class MultilinestringGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: str = "MultiLineString"
    coordinates: list[Coordinate2]


class Coordinate3Item(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Coordinate3(RootModel[list[Coordinate3Item]]):
    root: Annotated[list[Coordinate3Item], Field(min_length=4)]


class PolygonGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: str = "Polygon"
    coordinates: list[Coordinate3]


class Coordinate4(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class MultipolygonGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: str = "MultiPoint"
    coordinates: list[Coordinate4]


class Time1(Enum):
    NONE_TYPE_NONE = None


class GeometrycollectionGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: str = "GeometryCollection"
    geometries: list[
        PointGeoJSON
        | MultipointGeoJSON
        | LinestringGeoJSON
        | MultilinestringGeoJSON
        | PolygonGeoJSON
        | MultipolygonGeoJSON
        | GeometrycollectionGeoJSON
    ]


class RecordGeoJSON(TranspilerBaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str
    """
    A unique identifier of the catalog record.
    """
    type: str = "Feature"
    time: Time1 | Time | None = None
    geometry: (
        Time1
        | PointGeoJSON
        | MultipointGeoJSON
        | LinestringGeoJSON
        | MultilinestringGeoJSON
        | PolygonGeoJSON
        | MultipolygonGeoJSON
        | GeometrycollectionGeoJSON
        | None
    ) = None
    conforms_to: Annotated[list[str] | None, Field(alias="conformsTo")] = [
        "http://www.opengis.net/spec/ogcapi-records-1/1.0/req/record-core"
    ]
    """
    The extensions/conformance classes used in this record.
    """
    properties: RecordCommonProperties
    links: list[Link] | None = None
    link_templates: Annotated[
        list[LinkTemplate] | None, Field(alias="linkTemplates")
    ] = None


class Model(RootModel[RecordGeoJSON]):
    root: RecordGeoJSON


GeometrycollectionGeoJSON.model_rebuild()
